STL_DIR=../../STL/blades
IMG_DIR=../../images/blades
SRC_DIR=.
DEP_DIR=../../dep
GCD_DIR=../../gcode/blades
INI_DIR=../../slicing/blades
GIT_ROOT=../..
SOURCES=$(wildcard $(SRC_DIR)/*.scad)
include ../../utils/Makefile
