STL_DIR=../../STL/drawings
IMG_DIR=../../images/drawings
SRC_DIR=.
DEP_DIR=../../dep
GCD_DIR=../../gcode/drawings
INI_DIR=../../slicing
GIT_ROOT=../..
SOURCES=$(wildcard $(SRC_DIR)/*.scad)
include ../../utils/Makefile
