STL_DIR=../../STL/print_plate
AMF_DIR=../../AMF/print_plate
IMG_DIR=../../images
SRC_DIR=.
DEP_DIR=../../dep
GCD_DIR=../../gcode
INI_DIR=../../slicing/print_plate
GIT_ROOT=../..
SOURCES=$(wildcard $(SRC_DIR)/*.scad)
include ../../utils/Makefile
