STL_DIR=../../STL/print_plate
AMF_DIR=../../AMF
IMG_DIR=../../images/print_plate
SRC_DIR=.
DEP_DIR=../../dep
GCD_DIR=../../gcode/print_plate
INI_DIR=../../slicing/print_plate
GIT_ROOT=../..
SOURCES=$(wildcard $(SRC_DIR)/*.scad)
include ../../utils/Makefile
