STL_DIR=../../STL/4printing
IMG_DIR=../../images/4printing
SRC_DIR=.
DEP_DIR=../../dep
GCD_DIR=../../gcode/4printing
INI_DIR=../../slicing/generic
GIT_ROOT=../..
SOURCES=$(wildcard $(SRC_DIR)/*.scad)
include ../../utils/Makefile
