STL_DIR=../../STL/testing
IMG_DIR=../../images/testing
SRC_DIR=.
DEP_DIR=../../dep
GCD_DIR=../../gcode/testing
INI_DIR=../../slicing
GIT_ROOT=../..
SOURCES=$(wildcard $(SRC_DIR)/*.scad)
include ../../utils/Makefile
